[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
cursor = "#ffffff"
text = "#505050"

[colors.normal]
black = "#000000"
blue = "#6fb3d2"
cyan = "#76c7b7"
green = "#a1c659"
magenta = "#d381c3"
red = "#fb0120"
white = "#ffffff"
yellow = "#fda331"

[colors.bright]
black = "#000000"
blue = "#6fb3d2"
cyan = "#76c7b7"
green = "#a1c659"
magenta = "#d381c3"
red = "#fb0120"
white = "#ffffff"
yellow = "#fda331"

[colors.dim]
black = "#000000"
blue = "#6fb3d2"
cyan = "#76c7b7"
green = "#a1c659"
magenta = "#d381c3"
red = "#fb0120"
white = "#ffffff"
yellow = "#fda331"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 8.5
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
bold   = { family = "DejaVuSansM Nerd Font Mono", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font Mono", style = "Italic" }

[general]
live_config_reload = true

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "Y"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_title = true
padding = { x = 2, y = 2 }
